language: julia

os:
  - windows
  - linux

julia:
  - 1.11
  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: true

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

