name = "NeXLCore"
uuid = "93a0284f-3680-435e-8d39-dd6e52a1dbc8"
authors = ["Nicholas W.M. Ritchie <nicholas.ritchie@nist.gov>"]
repo-url = "https://github.com/usnistgov/NeXLCore.jl"
version = "0.3.9"

[deps]
BoteSalvatICX = "fe54227b-96c7-489b-9963-dd1ce2905f30"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
ConcurrentCollections = "5060bff5-0b44-40c5-b522-fcd3ca5cecdd"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NeXLUncertainties = "7127f3d6-1721-46bc-bb38-8fc703dd438e"
NumberIntervals = "978898f6-561e-11e9-3f66-13949d9e5c8a"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BoteSalvatICX = "2.0.1"
CSV = "0.10"
CategoricalArrays = "0.10"
Colors = "0.12"
Compose = "0.9"
ConcurrentCollections = "0.1"
CoordinateTransformations = "0.6"
DBInterface = "2.4"
DataDeps = "0.7"
DataFrames = "1.3"
Dierckx = "0.5"
FileIO = "1.11"
Gadfly = "1.3"
GeometryBasics = "0.3, 0.4"
ImageCore = "0.9"
LaTeXStrings = "1.3"
Measures = "0.3"
MeshCat = "0.15"
NeXLUncertainties = "0.2.11"
NumberIntervals = "0.2"
PeriodicTable = "1"
PhysicalConstants = "0.2"
Pluto = "0.19"
PlutoUI = "0.7"
Polynomials = "3"
QuadGK = "2.4"
Reexport = "1"
Requires = "1.2"
SQLite = "1.4"
StaticArrays = "1.4"
Tables = "1.7"
Unitful = "1.9"
Weave = "0.10"
julia = "1.6"

[extras]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
